### ISSUE TITLE
Does this end-to-end lane detection algorithm work for the situation which the number of lane is more than 4?

### ISSUE THREAD

**Issue by lymhust** [wvangansbeke/LaneDetection_End2End#1]
![image](https://user-images.githubusercontent.com/18476076/53007823-ff8f2c80-3472-11e9-8155-898772c17f6e.png)
Does this end-to-end lane detection algorithm work for the situation which the number of lane is more than 4? Thanks.

**Comment by wvangansbeke** [comment]
Yes, but ..... To keep it simple I used 4 output maps in order to detect a maximum of 4 lane lines. I used a second branch in de decoder which told me which one is present in the scene. This means that the maximum number of lane lines is a hyperparameter. So you can easily take more than 4.

A cleaner method is to use an instance segmentation approach, but we primarily wanted to focus on our differentiable least squares module from our paper. This module is compatible with whatever method you choose. See it as an extra layer of the network to make lane detection completely end-to-end. When I have time, I can also share my instance segmentation method if you want.

**Comment by lymhust** [comment]
> Yes, but ..... To keep it simple I used 4 output maps in order to detect a maximum of 4 lane lines. I used a second branch in de decoder which told me which one is present in the scene. This means that the maximum number of lane lines is a hyperparameter. So you can easily take more than 4.
> 
> A cleaner method is to use an instance segmentation approach, but we primarily wanted to focus on our differentiable least squares module from our paper. This module is compatible with whatever method you choose. See it as an extra layer of the network to make lane detection completely end-to-end. When I have time, I can also share my instance segmentation method if you want.

Thanks for your clear reply, we have tried several instance segmentation methods for lane detection purpose, such as:
https://arxiv.org/abs/1708.02551
http://cn.arxiv.org/abs/1802.05591 
If your method is different or superior to them, can you share some materials about it? Thanks.

**Comment by wvangansbeke** [comment]
Ok I'm glad I could help. The methods you mentioned should work fine. I designed a different method, but I'm not sure yet the accuracy is better. This will take some time to research.
