### ISSUE TITLE
How do we visualize the lane predictions similar to the clip in readme.md?

### ISSUE THREAD

**Issue by nykabhishek** [wvangansbeke/LaneDetection_End2End#10]

**Comment by wvangansbeke** [comment]
Hi @nykabhishek ,

This should be quite straightforward. The network produces the final lane line coefficients for a second degree polynomial. You can use this to draw a the curve on the image with the functions in OpenCV.

Kind regards,
Wouter

**Comment by huang45** [comment]
Hi, similar question from my side. After training I got model, could you kindly give the example running code? Thanks.

**Comment by wvangansbeke** [comment]
Hi @huang45,
It is actually very similar to the code to visualize the weight maps. To draw a solid line you can use the cv.polylines function and I used cv.circles to draw the dashed lines. Maybe take a look at the example code of tusimple. They show exactly what you have to do. 

I don't have time at the moment to share my code for this since I'm abroad. 

I hope this helps. 
Wouter

**Comment by huang45** [comment]
Hi Wouter,
Thanks for the reply. Sure I will try tusimple's code. By the way, could you share more about the the test mode? like your example for training phase:
`python main.py --image_dir /path/to/image/folder --gt_dir /path/to/ground_truth/folder --end_to_end True`
I tried to configure --test_mode, --clas, etc, but it seems no effect. Could you show me how do you do the test (without ground truth)?
Knowing that you are busy, sorry about that. But I really wish to reproduce your great work.

**Comment by Jeremy26** [comment]
@huang45 I have something here but not working yet 
https://github.com/wvangansbeke/LaneDetection_End2End/issues/12

**Comment by kingtaewoo** [comment]
hello. I want to make result like you @Jeremy26 ,
but I don't know where input the code. 
Did you input the code in utils.py or main.py??
