### ISSUE TITLE
Is there a pretrained model available? 

### ISSUE THREAD

**Issue by minghanz** [wvangansbeke/LaneDetection_End2End#14]
Hi. I am able to train the network on the 20% TuSimple data (~100 epochs), but the result is not very good when testing with images from other sources. I think the network need to be trained more thoroughly. Is there a pre-trained weight of the network available? Could you share it with us? Thank you!

**Comment by wvangansbeke** [comment]
Hi @minghanz
I have not yet looked at other datasets but you could be correct. A good initialization or pretraining could definitely boost the performance. Also, bear in mind that the first stage of the framework is the segmentation module. This module is not really robust for lane crossings, since we need to specify if the lane line is on the left or on the right side of the car. When crossing a lane, it is not clear if the crossed lane line is on the left or on the right. To solve this, you need either an extra branch or an instance segmentation module (=more elegant).
This was not the focus of this paper, since our contribution is the differentiable fitting module in our architecture (the second module). 
If I have some I might take look at it, since this would be very interesting.

Kind regards, 
Wouter
