### ISSUE TITLE
about Curve_parameters.json

### ISSUE THREAD

**Issue by huang45** [wvangansbeke/LaneDetection_End2End#15]
Hi @wvangansbeke , Could you please introduce how to generate curve parameter? Thanks.

**Comment by wvangansbeke** [comment]
Hi @huang45,
The file contains the coefficients of the second degree polynomials for the 4 lane lines in a birds eye view. To compute these parameters, I used the ground truth coordinates of the lane lines and fitted a line through them after transformation with the homography matrix. 

Each lane line is a new row in the matrix (final element in the dictionary) and the ordering is always relative to the position of the car. 

Hope this helps. 
Wouter

**Comment by huang45** [comment]
Hi @wvangansbeke , 
Got it. Are you using something like numpy.polyfit()? 
Another question, is that possible to output the polynomial of the curve on the image directly without transforming by the H matrix by your Network?

**Comment by wvangansbeke** [comment]
Hi @huang45,

Yes. I'm using numpy.polyfit to get the coefficients. 

You don't need to do the curve fitting in a bird's eye view. The reason why we use this instead of the original perspective is that you don't need a polynomial with a high order to get a good model for the lane lines. Hence, it should be easier for the network to converge. 

Kind regards.

**Comment by jiaofang1222** [comment]
When I use my own data, there is no ground truth coordinates of the lane lines.How should I get the curve parameters or how to get ground truth coordinates of the lane lines?How should I choose homography matrix？Looking forward to your reply.
