### ISSUE TITLE
Lane detection in LIDAR 

### ISSUE THREAD

**Issue by rfsch** [wvangansbeke/LaneDetection_End2End#16]
Hi 

I would need to detect lanes and borders from  a dataset which is LIDAR only. Is it possible ? 

Thanks

**Comment by wvangansbeke** [comment]
Hi @rfsch,

I find the setup quite strange since lane lines are almost not visible with a LiDAR  except from the small difference in the reflectance values. However, you'll need to detect lane lines even when they are not visible on the road. This is very difficult with a LiDAR. Using a camera, which is cheaper than a LiDAR sensor by multiple orders of magnitude, makes much more sense. 

Furthermore, LiDAR data is sparse which makes it harder for convolution operations. 

Hope this helps, 
Wouter

**Comment by rfsch** [comment]
Hi @wvangansbeke  thanks for your answer! 

How about the border of the road (curbs), shouldnt this be simpler ? The lidar produces some quite characteristic detections on the ground when a curb is hit. Any ideas ?  
I would just need to be able to approximately derive a centerline. Or maybe do you have an idea where I can find a LIDAR dataset with road boarder or lane annotations in xyz ? 

Thanks

Rupert

**Comment by wvangansbeke** [comment]
Hi @rfsch, 

I don't know if the curbs are easy to detect using LiDAR. It could be possible though but I don't know any datasets which have LiDAR and lane detection ground truth. Maybe the recent Nuscenes dataset but I'm not sure. 

Kind regards, 
Wouter
