### ISSUE TITLE
Where do the x, y coordinates come from?

### ISSUE THREAD

**Issue by YN-Tang** [wvangansbeke/LaneDetection_End2End#18]
Hi,
Congrats on your great work. I am being kind of confused on a point in your paper. 
You mentioned that there are two maps for the x, y coordinates, then, are they just representing the normalized pixel coordinates of every pixel in the image? e.g. The first colomn of X-map would be 0,0,0,0,0,0,0...? I don't see the point of having these maps if they are just pointing to themselves.
In this case, if you choose the first way of backprop, which is to update the coordinates, then do you mean that only the values in the X, Y-features maps are updating?
One last point, is there any correlation between the pixel and the location they are pointing to? Such as they might be pointing to a pixel of the same lane line?

**Comment by wvangansbeke** [comment]
Hi @YN-Tang, 

Thank you for your kind words. 

Since we perform line fitting in a bird's eye view perspective, we need to transform the coordinates using a homography matrix. These coordinates are represented with a X and Y map (indeed the first column of the X map consists of zeros). There is no backpropagation through these maps, because they are constants. The goal of the network is to predict the weights for the weighted least squares solution through which we backpropagate. The network can learn to predict the weights in the original perspective, since the coordinates are transformed to a bird's eye view perspective inside our differentiable fitting module. This makes it easier for the network to focus on the lane lines. After we transform the X and Y map, we can link the transformed (x, y) coordinate to the weight w for each pixel. These three elements are described as triplets in our paper. 

So, we need the X and Y map to solve our system of equations. The parameters for the lane lines can be determined using a weighted least squares approach which the network needs to learn after all. 

Hope this helps, 
Wouter

**Comment by YN-Tang** [comment]
Hi Wouter,

Thank you a lot for making it clear, now I see what you mean in the paper.
