### ISSUE TITLE
About the ground truth dataset?

### ISSUE THREAD

**Issue by ashergaga** [wvangansbeke/LaneDetection_End2End#20]
Why the images are all black in the ground truth dataset?I downloaded it in the link provided by the author.

**Comment by wvangansbeke** [comment]
Hi @ashergaga,

That sounds normal. The ground truth values are between 0 and 4 to identify the background and the four lane lines in the image. Since the maximum value of the png can be 255, it's hard to see the multiple instances. I should have saved it as a colormap to see the lane lines more clearly.

Kind regards,
Wouter

**Comment by ashergaga** [comment]
Thanks! Wouter. Your code is very useful for me.
