### ISSUE TITLE
about paper

### ISSUE THREAD

**Issue by Cverlpeng** [wvangansbeke/LaneDetection_End2End#21]
HI,wvangansbeke
Thanks,your good work
how do I visualize this heatmap in paper? this weight map?
![laneheatmap](https://user-images.githubusercontent.com/46803558/59650596-29eebd80-91b9-11e9-8579-807a2a908c51.png)

**Comment by wvangansbeke** [comment]
Hi @Cverlpeng,

These weight maps are the results of a toy example (different dataset), where the lines are clearly visible. We also used a smaller and simpler network with no downsampling. That's why the lines are so clear in this image. This was primarily used to see if the method made sense. If you want to generate this figure, you would need a clean lane detection dataset and a simple network (only a few layers). TuSimple has a lot different lane types such as metal dots, which makes it harder. But you can imagine that the appearance of the weight maps are primarily network dependent. 

Kind regards,
Wouter

**Comment by Cverlpeng** [comment]
thanks
Is this one of the channels of the feature map that has been selected for CNN output? Visualize it as an RGB image ？

**Comment by wvangansbeke** [comment]
Yes. You can take a look at the channels of the output of the CNN. Each channel represents a lane line after all. To visualize it, you can easily use `matplotlib` or something similar to save the figure.

**Comment by Cverlpeng** [comment]
> 是。您可以查看CNN输出的通道。毕竟每个通道代表一条车道线。要想象它，您可以轻松使用`matplotlib`或类似的东西来保存图形。

thank you very much!!!
