### ISSUE TITLE
how to detect all the lane not ego-lane as the readme show?

### ISSUE THREAD

**Issue by cuicuizhang1989** [wvangansbeke/LaneDetection_End2End#23]
hi,
thanks for your great job, but when I read the paper and the github code, all the experiment is about ego-lane, but readme gif in the github is multi lane, I wonder how to reach this result as you, please help, thanks a lot.

**Comment by wvangansbeke** [comment]
Hi @cuicuizhang1989,

In our paper we indeed focus on egolane detection. In order to detect multiple lanes more output maps are needed (this is provided in the code). For four lane lines, you need four output maps to solve four least squares problems. It is more complicated though, since there are not always four lane lines present in the image. You'll need to predict this with a separate branch in de decoder (is the lane line really present or not?). This is also provided in the code. 

I trained it quite a while ago for multi lane detection on the whole tusimple dataset and made the video. It is of course more difficult to train than with two lane lines. Therefore I mentioned some improvements in de discussion section of the README. 

Kind regards,
Wouter
