### ISSUE TITLE
Question about Normalized M to scaledup M conversion

### ISSUE THREAD

**Issue by harryhan618** [wvangansbeke/LaneDetection_End2End#25]
Hello,  in the source code, function [test_projective_transform](https://github.com/wvangansbeke/LaneDetection_End2End/blob/3ebe40b829b38034e4cf951b823914dafa765125/Networks/utils.py#L155) tranforms normalized M to image size M. I cannot understand why `M_scaledup` is set like that. 
![image](https://user-images.githubusercontent.com/10130410/60160827-c9025d80-9828-11e9-88cd-1aa5d0c79f64.png)

I'm asking why `M_scaledup[1, 0]` and `M_scaledup[2, 0]` are both 0? I think it ought to be: `M_scaledup[1, 0] = M[1, 0] / 2` and `M_scaledup[2, 0] = M[2, 0] / (2*resize-1)`

Here's my deduction. Perspective transform does following things:
![image](https://user-images.githubusercontent.com/10130410/60160527-20ec9480-9828-11e9-8562-423da6bd2891.png)
(where `a_{ij}` is item of normalized `M`)

So transforming normalized M to image size M basically does following things: 
![image](https://user-images.githubusercontent.com/10130410/60161409-1f23d080-982a-11e9-9873-e10903627eaa.png)
Thus `M_scaledup` should be: 
![image](https://user-images.githubusercontent.com/10130410/60161973-24354f80-982b-11e9-90e2-666d331ff6e1.png)

So every item matches your code except `M_scaledup[1, 0]` and `M_scaledup[2, 0]`.

**Comment by wvangansbeke** [comment]
Hi @harryhan618,

You derivation is correct. `M_scaledup[1, 0]` and `M_scaledup[2, 0]` are indeed 0 since a21 and a31 are zero. This is because I want a very specific transformation matrix where points with the same y (height) in the original perspective have the same y' in the transformed perspective. They are related by: 

![formula](https://user-images.githubusercontent.com/9694230/60165028-e28eaf80-97fe-11e9-9adb-15f7c4b8118f.png)

In fact y' is purely dependent on y and not on x. This means that both a21 and a31 need to be zero.
To see this, take you transformation matrix and calculate y'. You'll see that indeed a21 and a31 should be zero.

Hope this helps,
Wouter

**Comment by harryhan618** [comment]
Ok, I see. Thank you!
