### ISSUE TITLE
how to do normalization on my own dateset

### ISSUE THREAD

**Issue by BrandonZhong** [wvangansbeke/LaneDetection_End2End#31]
Hello, I am trying to train the network on my dataset, but I do not know the details on how to do the normalization  , can you  please show me more? Thanks!

**Comment by wvangansbeke** [comment]
Hi @BrandonZhong,

You'll need to know the resolution of the input images which you want to feed the network. This is necessary to compute the ground truth parameters and the normalized x, y-grid in the framework. You can just do this by dividision in order to get a grid with values between 0 and 1.

Best,
Wouter
