### ISSUE TITLE
questions about"switching lanes" and "detect 4 lines"

### ISSUE THREAD

**Issue by fenling** [wvangansbeke/LaneDetection_End2End#34]
hi Wouter:
in the issues i found “ I left some images out for training were the car is switching lanes, since you'll need an instance segmentation to handle those cases”
why these switching lanes cannot detect by the method.

"I used a second branch in decoder which told me which one is present in the scene" i can not find the second branch in the code? is it not released?
i can find“if self.nclasses > 3” support 4 lines.

"maximum number of lane lines is a hyperparameter"means I used n output maps in order to detect a maximum of n lane lines.(n is 5 or biger), is it right?

**Comment by wvangansbeke** [comment]
Hi @fenling,

I left the images where the car changes lane out to have a fair comparison for the egolane experiment. However I also did it on the whole dataset which converged. The problem is that the ground truth is ambiguous

**Comment by fenling** [comment]
hi Wouter:
1、in the whole dataset, did you do some changes on the change lanes? or do you have tricks on the  switching lanes?
2、“To detect a maximum of 4 lane lines, you will have to set nclasses to 4.” I should let the nclass to 4, and then set the nums n(n >4)，fine-tuning the model。

**Comment by wvangansbeke** [comment]
Hi @fenling,

1. There are multiple ways to solve the issue when changing lanes. One solution is to add an extra branch and detect this special case. You will also have to change the ground truth in order to make it unambiguous for those events. 

2. You can set 4 higher but if you don't have ground truth for 5 lane lines the network will not be able to learn a 5th line. This will result in a output map with very low probability. 

best,
Wouter
