### ISSUE TITLE
questions about "masked"

### ISSUE THREAD

**Issue by fenling** [wvangansbeke/LaneDetection_End2End#37]
hi Wouter:
1、in the code，Net.forward has self.net(input, end_to_end*self.pretrained)，the input image is normal image not a bird's view image?
2、the net output “masked” is showed in “save_weightmap”. I get the  "wm0_zeros" , the weighted picture is not matched with the detect line.as show in the picture.
i think the left ego_lines  in the wm0_zeros should be show， but cannot find left ego lines infor in the wm0_zeros.
![0007](https://user-images.githubusercontent.com/21993862/62450693-61342080-b79f-11e9-932b-e67a0f3f3c03.jpg)

**Comment by fenling** [comment]
![0007](https://user-images.githubusercontent.com/21993862/62451790-7f9b1b80-b7a1-11e9-9868-a1b10bf39f98.jpg)
is the bule image is generated by "wm0_zeros"、“wm1_zeros”

**Comment by wvangansbeke** [comment]
Hi @fenling,

1. The input of the network is indeed the original perspective (no bird's eye view).

2. `save_weightmap` shows the sum for all the weights maps.

**Comment by fenling** [comment]
hi Wouter:
Thank you for your reply.
1、the net output “masked” is the weight in original  perspective or bird's eye view?
2、save_weightmap get the weightmap_zeros(shape [1, 4, 256, 512]), wm0_zeros = weightmap_zeros.data.cpu()[0, 0].numpy(), wmo_zeros is the left ego-lines weight,
    i use ax1.imshow(wm0_zeros) , the result seems not right.
3、 how can i get the blue images?
![image](https://user-images.githubusercontent.com/21993862/62454944-e1f71a80-b7a7-11e9-8b5e-9c69780435e2.png)

**Comment by wvangansbeke** [comment]
Hi @fenling,

1. The output of the network is in the original perspective. We later transform the x-y coordinates to get to the bird's eye view perspective.

2. `wm0_zeros` is the first channel of `weightmap_zeros`. So that seems correct.

3. These weight maps are the results of a toy example (different dataset), where the lines are clearly visible. We also used a smaller and simpler network with no downsampling. That's why the lines are so clear in this image. This was primarily used to see if the method made sense. If you want to generate this figure, you would need a simple network (only a few layers). TuSimple has a lot different lane types such as metal dots, which makes it harder. But you can imagine that the appearance of the weight maps are primarily network dependent. If you want to get better visualizations, you can try pretraining on two lane lines.

Kind regards,
Wouter
