### ISSUE TITLE
How can get the transformation matrix H?

### ISSUE THREAD

**Issue by WBinke** [wvangansbeke/LaneDetection_End2End#4]
In your paper, the transformation matrix H is kownn, but I don't know how to get the matrix, is it fixed to every image in the tusimple dataset according to the camera parameters, or it's dynamic due to different image?  Thanks!

**Comment by wvangansbeke** [comment]
You're correct. I used the same homography matrix for every image. This homography matrix is more or less valid for all images in the TuSimple dataset since the road stays more or less flat.

Kind regards,
Wouter.

**Comment by fuchangjie** [comment]
@wvangansbeke So, do you think the Matrix H will influence the performance of estimating the weight maps when the road is not flat? What if the input of the deep network is perspective transformed?

BR. Thanks.

**Comment by wvangansbeke** [comment]
Hi @fuchangjie,
The reason why we don't transform the input is that the line features can be more difficult to extract by the network in a bird's eye view perspective. This was our assumption but it can be interesting to experiment with this though. Introducing a variable transformation matrix seems a straightforward solution for this.

Kind regards

**Comment by fuchangjie** [comment]
Hi @wvangansbeke ,
Yes, I agree with the worry about the feature extracting performance in the bird's eye view. But it's also not easy to get the transformation matrix when driving. So if it's not proper to fit a line with a parabola in front view, do you ever try other curves like spline may be (it's harder i know) to fit the lines in original image?

BR. Thanks.

**Comment by wvangansbeke** [comment]
Hi @fuchangjie 
You're completely correct about this. It could be better to model the lane lines with splines, since the transformation matrix is not perfect. However, stability could be an issue during training. Using a Cholesky decomposition might solve this problem. I did not try this yet, but we mention this possibility in the paper.

Kind regards.
Wouter

**Comment by fuchangjie** [comment]
Hi @wvangansbeke 
Ok, and thank you for you time.

BR. Thanks.

**Comment by wvangansbeke** [comment]
Hi @fuchangjie 
No problem. Thank you for your interest.

Kind regards.

**Comment by harryhan618** [comment]
Hi, thanks for sharing! May I ask what exactly do you do to calculate the transformation matrix for bird-view?

**Comment by wvangansbeke** [comment]
Hi @harryhan618,

Is simply used 4 points in order to define the transformation matrix. I used 4 corresponding points (4 source points and 4 destination points) as input for `cv2.getPerspectiveTransform`. This will give the homography matrix. I chose the points such that horizontal lines in the original image are also parallel in the transformed image. 

Hope this helps.

**Comment by harryhan618** [comment]
Thank you! All the mystery is solved in function `get_homography` in the file `Dataloader/Load_Data_new.py`.
