### ISSUE TITLE
Can you provide us with your own best weights?

### ISSUE THREAD

**Issue by masouduut94** [wvangansbeke/LaneDetection_End2End#62]
The project sounds really cool.
I was wondering if you could update the repository with some pretrained networks. 
That could save so much time for evaluating
and also can I ask you how can I possibly make the model more robust in curvy roads. do I need to gather dataset or there are good datasets available?

Thank you so much.

**Comment by wvangansbeke** [comment]
Hi @masouduut94,

For egolane detection you only need to detect the line on the left and right of the car. It should be fairly easy to get the numbers. For the multi-lane detection robustness can be an issue, so I would like to refer you to the README section where we discuss this. I will probably retrain it and share the weights with my own code since it has been a while ago. I don't know about any specific datasets atm, except maybe CULANE dataset.

Best,
Wouter
