### ISSUE TITLE
How to run inference on custom data

### ISSUE THREAD

**Issue by ma-siddiqui** [wvangansbeke/LaneDetection_End2End#70]
Hi,
I don't have ground truth and I want to run model on images to see lanes, how would that be possible? Please provide brief information to do this.

Thanks,

**Comment by asdsdlgl** [comment]
I have the same problem. Is there a solution for this now?

Thanks

**Comment by ma-siddiqui** [comment]
@wvangansbeke it would be great favor if you can specify how to run inference on custom data so we can test your state of the art model.

Thanks,

**Comment by wvangansbeke** [comment]
Hi @ma-siddiqui, 

You would first have to train your model on your own data or (since you don't have ground truth) on a different dataset with ground truth. You need the ground truth to compute the lane-line coefficients for all images after all, e.g. for a second degree polynomial. Then run inference on your own data. 
Best, 
Wouter
