### ISSUE TITLE
about using the subset of tusimple as dataset

### ISSUE THREAD

**Issue by zhaoedf** [wvangansbeke/LaneDetection_End2End#76]
when I was using the subset of tusimple as dataset, I encounted some errors. It appears that you write an assertion in you code, saying that the amount of the dataset has to be 4036(may be not correct). 
Then I simply commented the assertion. however, it seemed that in your code(Load_data_new.py) you have defined a exact amount of a dataset. 

I was wondering if you can give some advice on this problem, cos it's troublesome to download the fullset of tusimple.

Thank you in advance!

**Comment by wvangansbeke** [comment]
Hi @BUgxCreator,

Indeed, you can download the subset or download the complete dataset of TuSimple. Our subset was meant as a toy-example to show that this approach can optimize towards the lane-line coefficients directly. Feel free to change the dataloading part if you want to include more or less samples. The reason why we used a subset, was to exclude images where the car was changing lanes. Since we do not perform instance segmentation, the network has difficult time when the car is not in the middle of the lane. 

Feel free to experiment with these edge cases. 

Best, Wouter

**Comment by zhaoedf** [comment]
> Hi @BUgxCreator,
> 
> Indeed, you can download the subset or download the complete dataset of TuSimple. Our subset was meant as a toy-example to show that this approach can optimize towards the lane-line coefficients directly. Feel free to change the dataloading part if you want to include more or less samples. The reason why we used a subset, was to exclude images where the car was changing lanes. Since we do not perform instance segmentation, the network has difficult time when the car is not in the middle of the lane.
> 
> Feel free to experiment with these edge cases.
> 
> Best, Wouter

thank you, i will try
