### ISSUE TITLE
How to modify the Dataset for backprojection

### ISSUE THREAD

**Issue by kingtaewoo** [wvangansbeke/LaneDetection_End2End#79]
Hello, I'm studying your thesis.
and I Successfully executed the bird-eyes view. and now I want to execute the back- projection.
and I know I need 3625 pieces of data set, but I want to try 2535 Data set(in the bird-eyes view)

so, how should I modify it? can I run the backprojection with 2535 data set?
I tried 
1. change labels (changed label was in the bird's eyes view) , + lane ordered.jason.   ---> out of range error
2. change the number in the Load data .py ( back projection)                                 --> Assertion error

Sincerely

**Comment by wvangansbeke** [comment]
Hi @kingtaewoo,

You need to make sure everything matches. So the ground truth should match the input image when loading the data. 
So maybe visualize the ground truth first and start from 2 lanes. This should go pretty easy. Then you can upscale it.

I included the assertion because the focus of this repository was egolane detection (=2 lane lines). If you want to include more data or more lanes, feel free to do so but take the tips of the README into account. (So you can just remove the assertion if necessary.) Depending on the data, network and amount of lanes, you might require more explicit supervision which is not that surprising. 

Best, 
Wouter
