### ISSUE TITLE
run train error

### ISSUE THREAD

**Issue by huang45** [wvangansbeke/LaneDetection_End2End#9]
hi, I tried to run you model by:
`python main.py --image_dir {mypath}/tusimple/DATASET/images/ --gt_dir {mypath}/tusimple/DATASET/ground_truth/  --end_to_end True`

but got the error like this:
```
0it [00:00, ?it/s]Batch with idx [1375  536 1493 1366  750 1664 1031 1017] skipped due to singular matrix
tensor should be 2 dimensional
```
The Dataset is downloaded form your link. Appropriate if you could help by this.

**Comment by wvangansbeke** [comment]
Hi @huang45,

Maybe remove the "try - except" in the main file to see which error occurs exactly. If you train in an end-to-end fashion, the matrix in the least squares expression could become singular theoretically. This means that this matrix is not invertible. In pratice this almost never happens. Once the network starts looking at the lane lines, the matrix should not be singular. This could happen occasionally though at the start of the training proces depending on the initialization and shuffle order of dataloader. That's why I skip the batches which throw an error. Since I never found this to be a fundamental problem, I suspect there is another problem but the exact error is disguised by the try-except clause. 

If you do find this to be a problem in your environment, you can try pretraining with a few images and segmentation ground truth so the network is initialized correctly. I really don't think this is necessary but it will definitely add robustness.

Kind regards,
Wouter

**Comment by huang45** [comment]
Thanks for the quick response. I tried to remove except code, but still got the Error as following:

> Init model: 'erfnet'
> Number of parameters in model ERFNET is 2.063M
> 
>  => Start train set for EPOCH 89
> 0it [00:00, ?it/s]
> Traceback (most recent call last):
>   File "main.py", line 522, in <module>
>     main()
>   File "main.py", line 214, in main
>     output_net, outputs_line, outputs_horizon = model(input, args.end_to_end)
>   File "/home/lzh/anaconda3/envs/test/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/lzh/Work/LaneDetection_End2End/Networks/LSQ_layer.py", line 323, in forward
>     beta0, beta1, beta2, beta3 = self.ls_layer(masked, grid)
>   File "/home/lzh/anaconda3/envs/test/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/lzh/Work/LaneDetection_End2End/Networks/LSQ_layer.py", line 126, in forward
>     Z_inv = torch.inverse(Z)
> RuntimeError: tensor should be 2 dimensional
> 
> 

And I tried to set --end_to_end False, got the same result. I just finished these: setup the environment, download your dataset and train without changing code. Could you help to check if you have this problem by a new train process? Thanks a lot.

**Comment by wvangansbeke** [comment]
Ok I see.
Update pytorch to 1.0 and it should be fine. You probably have an older version of Pytorch, since torch.inverse() cannot operate on batches (3 dimensional) in the older versions.

Hope this helps

**Comment by huang45** [comment]
Yes, it is! My fault to use the wrong Conda environment. The train looks like working well. Thanks again!
